name: check_code_quality
on: pull_request
jobs: 
  black: # mettre le nom qu'on souhaite ici
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - run: | #bash multi-lignes
          python -m pip install --upgrade pip
          pip install black
      - run: |
          black --check --verbose .


